import { useEffect,useRef } from "react";
import type { DemoFramePacket,TrackSnapshot } from "../contracts";
import { drawMirroredImage,mirrorHorizontal,mirrorNormalizedBoxX } from "../mirroring";
const colors={inactive:"#9aa8a2",qualifying:"#ffbd59",selected:"#74f5b5",group:"#c9a8ff",danger:"#ff6f70",gaze:"#50d8ff"};
function role(t:TrackSnapshot,p:DemoFramePacket){const visual=t.track_id===p.visual_target_id,engaged=t.track_id===p.selected_target_id;return{visual,engaged,label:visual&&engaged?"EYES + ENGAGED":visual?"EYES":engaged?"ENGAGED":""}}
function color(t:TrackSnapshot,p:DemoFramePacket){const target=role(t,p);if(t.stale||p.attention_state==="FAULT")return colors.danger;if(target.engaged)return colors.selected;if(target.visual)return colors.gaze;if(p.attention_state==="GROUP_ATTENTION"&&t.attention_score>=.65)return colors.group;if(t.state==="QUALIFYING")return colors.qualifying;return colors.inactive}
function arrow(c:CanvasRenderingContext2D,x:number,y:number,dx:number,dy:number,shade:string,width=2){c.strokeStyle=shade;c.fillStyle=shade;c.lineWidth=width;c.beginPath();c.moveTo(x,y);c.lineTo(x+dx,y+dy);c.stroke();const a=Math.atan2(dy,dx);c.beginPath();c.moveTo(x+dx,y+dy);c.lineTo(x+dx-Math.cos(a-.55)*9,y+dy-Math.sin(a-.55)*9);c.lineTo(x+dx-Math.cos(a+.55)*9,y+dy-Math.sin(a+.55)*9);c.closePath();c.fill()}
function backdrop(c:CanvasRenderingContext2D,w:number,h:number){c.fillStyle="#17211e";c.fillRect(0,0,w,h);const horizon=h*.68;c.strokeStyle="rgba(150,186,171,.12)";c.lineWidth=1;for(let i=0;i<12;i++){c.beginPath();c.moveTo(0,horizon+i*i*2.4);c.lineTo(w,horizon+i*i*2.4);c.stroke()}for(let i=-5;i<=5;i++){c.beginPath();c.moveTo(w/2,horizon);c.lineTo(w/2+i*w*.24,h);c.stroke()}c.fillStyle="rgba(116,245,181,.05)";c.fillRect(w*.36,h*.1,w*.28,h*.7);c.fillStyle="#a9bbb4";c.font="600 13px ui-monospace";c.fillText("LOCAL VISION PREVIEW",18,28)}
export function VideoStage({packet,isFixture,connectionStale}:{packet:DemoFramePacket|null;isFixture:boolean;connectionStale:boolean}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas||!packet)return;const b=canvas.getBoundingClientRect(),r=devicePixelRatio||1;canvas.width=Math.max(1,Math.round(b.width*r));canvas.height=Math.max(1,Math.round(b.height*r));const c=canvas.getContext("2d");if(!c)return;c.scale(r,r);const w=b.width,h=b.height;
    const overlay=()=>{c.save();const roi={x:w*.34,y:h*.16,width:w*.32,height:h*.66};c.strokeStyle="rgba(116,245,181,.75)";c.setLineDash([7,6]);c.lineWidth=1.5;c.strokeRect(roi.x,roi.y,roi.width,roi.height);c.setLineDash([]);c.fillStyle="rgba(116,245,181,.08)";c.fillRect(roi.x,roi.y,roi.width,roi.height);c.fillStyle="#a8f7cc";c.font="600 11px ui-monospace";c.fillText("ATTENTION ROI",roi.x+8,roi.y+17);
      packet.tracks.forEach(t=>{const[xn,yn,wn,hn]=t.bbox,x=mirrorNormalizedBoxX(xn,wn)*w,y=yn*h,bw=wn*w,bh=hn*h,target=role(t,packet),shade=color(t,packet);c.strokeStyle=shade;c.lineWidth=target.engaged?3:target.visual?2.5:1.5;c.strokeRect(x,y,bw,bh);c.fillStyle="rgba(11,18,16,.88)";c.fillRect(x,Math.max(0,y-26),Math.min(bw,250),26);c.fillStyle=shade;c.font="700 12px ui-monospace";c.fillText(`T${t.track_id}  ${(t.attention_score*100).toFixed(0)}%  ${target.label||t.state}`,x+7,Math.max(17,y-9));const ox=x+bw/2,oy=y+bh*.26;if(t.raw_head_pose)arrow(c,ox,oy,mirrorHorizontal(t.raw_head_pose.yaw)*1.65,t.raw_head_pose.pitch*1.65,"rgba(255,255,255,.35)",1.2);if(t.filtered_head_pose)arrow(c,ox,oy,mirrorHorizontal(t.filtered_head_pose.yaw)*2.2,t.filtered_head_pose.pitch*2.2,shade);if(t.gaze)arrow(c,ox,oy+9,mirrorHorizontal(t.gaze.x)*85,t.gaze.y*85,colors.gaze);if(t.stale){c.fillStyle="rgba(255,60,70,.2)";c.fillRect(x,y,bw,bh)}});
      c.fillStyle="rgba(8,13,12,.84)";c.fillRect(14,h-42,256,28);c.fillStyle="#d9e4df";c.font="600 12px ui-monospace";c.fillText(`FRAME ${packet.frame_id} · ${packet.mode} · ${packet.tracks.length} TRACKS`,24,h-23);
      if(isFixture){c.textAlign="right";c.fillStyle="#ffbd59";c.font="800 12px ui-monospace";c.fillText("TEST FIXTURE · NOT MODEL OUTPUT",w-18,28);c.textAlign="left"}
      if(connectionStale||packet.stale_fields.length){c.fillStyle="rgba(255,55,65,.88)";c.fillRect(w/2-84,14,168,30);c.fillStyle="#fff";c.textAlign="center";c.font="800 12px ui-monospace";c.fillText("STALE RESULT",w/2,34);c.textAlign="left"}c.restore()};
    if(!packet.image_jpeg.length){backdrop(c,w,h);overlay();return}const blob=new Blob([packet.image_jpeg.slice().buffer],{type:"image/jpeg"}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{drawMirroredImage(c,img,w,h);overlay();URL.revokeObjectURL(url)};img.onerror=()=>{backdrop(c,w,h);overlay();URL.revokeObjectURL(url)};img.src=url;
  },[packet,isFixture,connectionStale]);
  if(!packet)return <div className="video-stage video-stage--empty" role="status"><span className="loader-orbit"/><strong>Waiting for local inference</strong><span>The video and overlays will arrive in one frame-aligned packet.</span></div>;
  return <div className="video-stage"><canvas ref={ref} aria-label={`Live vision frame ${packet.frame_id}, with ${packet.tracks.length} tracked faces`}/><div className="sr-only" data-testid="frame-alignment">Frame {packet.frame_id}; overlay frame {packet.frame_id}; state frame {packet.frame_id}; visual target {packet.visual_target_id??"none"}; attention target {packet.selected_target_id??"none"}</div><div className="video-legend"><span><i className="legend-dot head"/>Head pose</span><span><i className="legend-dot gaze"/>Visual eyes</span><span><i className="legend-dot selected"/>Attention</span></div></div>;
}
